# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..exports import geometry

class Geometry(Protocol):

    @abstractmethod
    def distance(self, a: geometry.Point, b: geometry.Point) -> float:
        raise NotImplementedError

    @abstractmethod
    def area_rectangle(self, r: geometry.Rectangle) -> float:
        raise NotImplementedError

    @abstractmethod
    def area_circle(self, c: geometry.Circle) -> float:
        raise NotImplementedError

    @abstractmethod
    def area_triangle(self, t: geometry.Triangle) -> float:
        raise NotImplementedError


class Store(Protocol):
    pass

class Lang(Protocol):

    @abstractmethod
    def format_message(self, name: str) -> str:
        raise NotImplementedError

    @abstractmethod
    def reverse_string(self, s: str) -> str:
        raise NotImplementedError


